battle_arena|2589599249|A strategic scenario based on a very interesting setting of Demons vs Humans!\n\nmade by Zeo-Tripathi|https://glest.io/mods/scenarios/battle_arena.7z|https://glest.io/mods/scenarios/battle_arena.jpg|
island_survival|323458548|An alpha version of the Island Survival scenario for the game Glest\n\nCredits to:\n-The Glest team for their development of the awesome Glest game\n-titiger, who took the initative to develop such a tediously long scenario and developed almost all of the units in this scenario\n-Andy, for forking the game into ZetaGlest and including it in the built-in scenarios\n-MathuSum Mut, who did a complete revision of the code, fixed bugs and extended the story. It is yet to be finished|https://glest.io/mods/scenarios/island_survival.7z|https://glest.io/mods/scenarios/island_survival.jpg|
apocalypse|3119439899|An epic real time strategy multiplayer scenario, based on an apocalyptic scene,\nwhere you and your friends are the last few humans on earth,\nbattling a great dark power which has been released from the hellish realm.\nThis dark power is called the Doom Bringer, and it is taking over the world.\nYou must work with your friends,\nto defeat the evil host of the Doom Bringer,\nand stop the apocalyptic invasion of demons.\n\nMade by Keith Sammut|https://glest.io/mods/scenarios/apocalypse.7z|https://glest.io/mods/scenarios/apocalypse.png|
lord_of_the_land|1678765098|You are a worker living in a village and you need to work your way \nup to be the Lord.|https://glest.io/mods/scenarios/lord_of_the_land.7z|https://glest.io/mods/scenarios/lord_of_the_land.jpg|
seventh_element|3193706531|A quest to defeat the 4 demonic guardians, and restore the titans' rule!\n\nMade by Keith Sammut|https://glest.io/mods/scenarios/seventh_element.7z|https://glest.io/mods/scenarios/seventh_element.jpg|
atlantis|610496465|An incredible wild mission based on the pursuit of the gateway to the great city of Atlantis\n\nMade by Keith Sammut|https://glest.io/mods/scenarios/atlantis.7z|https://glest.io/mods/scenarios/atlantis.png|
mission_break_out|578467296|A military break out scenario|https://glest.io/mods/scenarios/mission_break_out.7z|https://glest.io/mods/scenarios/mission_break_out.jpg|
tartarus|883614765|A Hard Hellish Glest Scenario With Devastating Monsters And Demons.\n Also featuring obstacles like lava, volcanos and thunderstorms!\n\nMade by Keith Sammut|https://glest.io/mods/scenarios/tartarus.7z|https://glest.io/mods/scenarios/tartarus.jpg|
wild_hunt|2430072457|A scenario based on the fight for survival\n\nMade by Keith Sammut|https://glest.io/mods/scenarios/wild_hunt.7z|https://glest.io/mods/scenarios/wild_hunt.jpg
